spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.20.2.210:3306/wage?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: liu
    password: DM@0cqupt.lanshan
juzi:
  system:
    application-home-path: /home/lxxc
